### ISSUE TITLE
Error with installing (pipenv, pip)

### ISSUE THREAD

**Issue by koddr** [EngageSports/django-multiple-auth#1]
Hello, @martync and thanks for this Django package.
I judge by description, but for my projects this package will be just a rescue!

I use awesome [pipenv](https://docs.pipenv.org) Python Dev Workflow, but similar error is showing to me by `pip install` command too.

After `pipenv install django-multiple-auth`, I get this error:

```bash
Installing django-multiple-auth…
Collecting django-multiple-auth
  Downloading django-multiple-auth-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pip-build-747ovvwk/django-multiple-auth/setup.py", line 7, in <module>
        with open('%s.md' % file_) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
    
    ----------------------------------------

Error:  An error occurred while installing django-multiple-auth!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pip-build-747ovvwk/django-multiple-auth/
```

I think, error rises because `FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'`.

Can you fix this please?

**Comment by martync** [comment]
Thanks for reporting this, I will try to fix this asap

**Comment by koddr** [comment]
@martync great! 👍 

Some idea about this error. Maybe use absolute path for `with open(...)` function? Because `pip` doesn't found `CHANGELOG.md` at current (temp) directory when init.

**Comment by martync** [comment]
@koddr I've forgot the manifest, please let me know if this is fixed for you, and I'll close the issue

**Comment by koddr** [comment]
@martync that's okay, thanks!

```bash
Installing django-multiple-auth…
Collecting django-multiple-auth
  Downloading django-multiple-auth-1.2.tar.gz
Building wheels for collected packages: django-multiple-auth
  Running setup.py bdist_wheel for django-multiple-auth: started
  Running setup.py bdist_wheel for django-multiple-auth: finished with status 'done'
  Stored in directory: /Users/koddr/Library/Caches/pip/wheels/df/6f/d1/4a24208f6e9bbb56f5471b18bfec8b58edfce4b4035e1292d8
Successfully built django-multiple-auth
Installing collected packages: django-multiple-auth
Successfully installed django-multiple-auth-1.2

Adding django-multiple-auth to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (0227d3)!
```
